disable = ["system"]
cleanup = true

[git]
repos = [
    "~/.skim",
    "~/LanguageServers/elixir-ls",
    "~/bin/motislide"
]

[commands]
"Vim Packs" = "pack update"
"Rust" = "rustup update"
"Elixir LS" = "cd ~/LanguageServers/elixir-ls && mix deps.get && mix compile && mix elixir_ls.release -o release"
