git_repos = [
    "~/.skim",
    "~/LanguageServers/elixir-ls",
    "~/LanguageServers/rust-analyzer"
]

cleanup = true

[commands]
"Tmux plugins" = "~/.tmux/plugins/tpm/bin/update_plugins all"
"Oh My Zsh" = "upgrade_oh_my_zsh"
"Zsh Plugins" = "zplug update"
"Brew" = "sh ~/.brew"
"Vim Packs" = "pack update"
"Rust" = "rustup update"
"Cargo" = "cargo install-update -a"
"Rust Analyzer" = "cd ~/LanguageServers/rust-analyzer && cargo xtask install --server"
"Elixir LS" = "cd ~/LanguageServers/elixir-ls && mix deps.get && mix compile && mix elixir_ls.release -o release"
